Dockerfile.dev

FROM openjdk:8-jdk-alpine
VOLUME /tmp
COPY ./target/GroceryBookingApp.jar /GroceryBookingAp.jar
ENTRYPOINT exec java -cp GroceryBookingApp.jar -Dloader.main=com.ps.nextgen.GroceryBookingApplication org.springframework.boot.loader.PropertiesLauncher --spring.profiles.active=dev
